### ISSUE TITLE
[BUG] Once again not supported for servers

### ISSUE THREAD

**Issue by red2blue** [AnonymousHacker1279/ImmersiveWeapons#62] opened 2021-12-18 06:23 UTC
Spent another fulll day trying to figure out why the hell I cannot join my server. It was due to your mod. Seems like its just made for single player. i really want it in my modpack but man... please start testing your mod on **servers** since you clearly aren't doing so when you put it out in production. 

Server starts, but clients cannot join server. Your mod is destroying the data processor  
![image](https://user-images.githubusercontent.com/35115304/146631642-5ed3b2c1-8b27-446b-a7bb-4e1ab682bf03.png)

Client latest: https://pastebin.com/sZnTzhhV
Debug: https://gist.github.com/red2blue/7faacae33dd42745440ddd113cbe8ede
Server latest: https://gist.github.com/red2blue/1d4be5a6150baed1bd3f998ced999151

Please change 
![image](https://user-images.githubusercontent.com/35115304/146631675-f077522c-d0ff-475a-b8a3-eb2d6648dc04.png)
to alpha

**Comment by red2blue** [comment] 2021-12-18 06:23
this is with your latest update btw.

**Comment by AnonymousHacker1279** [comment] 2021-12-18 17:21
It's marked as a pre-release for a reason, you should expect potential bugs. However, I fail to see how in the logs that my mod is causing issues; nothing points directly to Immersive Weapons. My best guess is that you have other mods scattered about that are breaking something. I see KubeJS modifying data packs, perhaps that's the source of your issue?

I have no trouble setting up a server using my mod. 
![image](https://user-images.githubusercontent.com/48810167/146649912-9adb787b-4c0d-48e3-9c67-c3cb1cb8dc9a.png)

**Comment by Fury-The-Coder** [comment] 2021-12-18 17:31
I have also read the logs two or three times and have not found any issues relating to immersive weapons. Instead of checking all of your mods to see which one was the real issue I can very clearly tell you jumped straight to the mod you have had issues with in the past, which have been fixed. You clearly just lacked the discipline to check what the real issue was and instead you left a really rude issue report and complained about it in other locations that have no involvement with Immersive Weapons. Skill issues...
![image](https://user-images.githubusercontent.com/48967486/146650372-5c6158d0-0dbd-4d37-aabf-5c26b5795199.png)

**Comment by red2blue** [comment] 2021-12-18 17:59
> I have also read the logs two or three times and have not found any issues relating to immersive weapons. Instead of checking all of your mods to see which one was the real issue I can very clearly tell you jumped straight to the mod you have had issues with in the past, which have been fixed. You clearly just lacked the discipline to check what the real issue was and instead you left a really rude issue report and complained about it in other locations that have no involvement with Immersive Weapons. Skill issues... ![image](https://user-images.githubusercontent.com/48967486/146650372-5c6158d0-0dbd-4d37-aabf-5c26b5795199.png)

LMFAO I spent 6 hours before I "jumped" to your mod. I went through Tons of mods, thinking you fixed the server issue. Did you not read what I said? Jesus christ. go fuck yourself.

**Comment by red2blue** [comment] 2021-12-18 18:03
> 

Who are you? Since you want to screenshot shit I said, That I also said here, why don't you read the last 6 hours of what I was writing in that channel, clearly showing I spent all day looking for the culprit, and not "**jum,ping to what I last had problems with**. If I did that in the first place I wouldn't have been in that discord asking for help all day now would i? go away troll

**Comment by red2blue** [comment] 2021-12-18 18:04
> Skill issues...

Skill issues with some guy with developer as his title in GH and no repos. Cute.

**Comment by AnonymousHacker1279** [comment] 2021-12-18 18:05
Guys, let's not stalk each other on Discord now... 

It looks like KubeJS is causing issues, and that's all I can find. Perhaps it's a configuration there? I cannot reproduce the issue. As you saw in my comment (not @Fury-The-Coder's, he is not a developer on this project), I was able to successfully start and join a server with my mod loaded.

**Comment by red2blue** [comment] 2021-12-18 18:06
> Guys, let's not stalk each other on Discord now...
> 
> It looks like KubeJS is causing issues, and that's all I can find. Perhaps it's a configuration there? I cannot reproduce the issue. As you saw in my comment (not @Fury-The-Coder's, he is not a developer on this project), I was able to successfully start and join a server with my mod loaded.

Apologies. I realized that and deleted that comment. I will open a ticket with KJS

**Comment by AnonymousHacker1279** [comment] 2021-12-18 18:11
I do want to mention that I'm not 100% certain that it's KubeJS. That was just the only thing I could find that was modifying recipe serializers and it pointed to a few mods that were being changed, mine being included. 

Best of luck, I hope you get the problem solved.

**Closed by AnonymousHacker1279** 2021-12-18 18:11 UTC
Labels: question, server-side

**Comment by red2blue** [comment] 2021-12-18 18:14
That makes sense though as that is what KubeJS is all about. You can use it to modify recipes with javascript. do you think it's possible that there's a conflict with IW not allowing it to be accessed by KubeJS by chance?

**Comment by AnonymousHacker1279** [comment] 2021-12-18 18:17
I doubt that, as there isn't anything I do to stop it from being modified. The datapack portion of my mod is setup properly as well. KubeJS should be able to access it.

**Comment by red2blue** [comment] 2021-12-18 18:20
> I doubt that, as there isn't anything I do to stop it from being modified. The datapack portion of my mod is setup properly as well. KubeJS should be able to access it.

I see. damn. looks like its back to the drawing boards. I'll let you know what I find out.
