### ISSUE TITLE
Server crash when stepped on a bear trap

### ISSUE THREAD

**Issue by AnfenPants** [AnonymousHacker1279/ImmersiveWeapons#42] opened 2021-08-17 10:08 UTC
**Describe the bug**
[crash-2021-08-17_09.53.34-server.txt](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/6998989/crash-2021-08-17_09.53.34-server.txt)

**To Reproduce**
Steps to reproduce the behavior: step on a bear trap.

**Expected behavior**
Server is not supposed to crash.

**Screenshots**
None

**Setup**
 - Forge: 37.0.32
 - ImmersiveWeapons: 1.7.1
 - Other mods: It's in the bug report file.

**Comment by AnonymousHacker1279** [comment] 2021-08-17 20:19
The issue is related to a client side class being accessed from the server. Should be relatively straightforward to fix but I'm currently busy with school.

I'll try to have a bugfix by the end of this week, no promises though.

**Comment by AnonymousHacker1279** [comment] 2021-08-19 01:00
This has been fixed in the latest v1.8.0 release. Thanks for the report.

**Closed by AnonymousHacker1279** 2021-08-19 01:00 UTC
Labels: bug, crash
