### ISSUE TITLE
Immersive Weapons Diamond Shards Recipe Overwrites Vanilla Diamond Recipe [Diamond Block=9 Diamonds]

### ISSUE THREAD

**Issue by Morabert** [AnonymousHacker1279/ImmersiveWeapons#34] opened 2021-07-20 23:03 UTC
The Mod effectively locks Diamond Blocks once Crafted [the diamond recipe which makes diamonds from diamond blocks is overwritten by the diamond shard to diamond recipe]

In addition when trying to remove the mod it creates Datapack errors which means it can't be taken out of the mods folder.

**Comment by AnonymousHacker1279** [comment] 2021-07-21 02:29
I am unable to reproduce this in the latest version of Immersive Weapons. What version are you using?
And for datapack errors, please upload your ``debug.log`` file so I can see what went wrong.

Your ``debug.log`` file can be found under your ``.minecraft`` folder, in the ``logs`` directory.

**Comment by Morabert** [comment] 2021-07-22 18:10
[debug-1.log.gz](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/6864359/debug-1.log.gz)

**Comment by AnonymousHacker1279** [comment] 2021-07-22 19:35
From what I can gather from the log, you are using a very outdated version of Immersive Weapons (1.0.3). Try updating to a newer version. 

If you are updating to a version newer than v1.2.0 (latest is v1.3.4), you will need to use Java 16 instead of the default Java 8 that Minecraft ships. I recommend using [AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot). In your launcher profile, click More Options and under Java Executable, browse to where you installed Java, and select ``javaw.exe``. It's under the ``bin`` folder. For example, mine is at ``C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot\bin\javaw.exe``

Next, you'll need to add two arguments to your launcher. Directly under the Java Executable is JVM Arguments. Copy-paste this at the end of the arguments list: 
```--add-exports=java.base/sun.security.util=ALL-UNNAMED
--add-opens=java.base/java.util.jar=ALL-UNNAMED
```
This allows Forge to run with Java 16 on 1.16.5. It will not be required for 1.17.1 when Forge releases. Additionally, I would recommend updating your Forge to the latest version. They released a big update today.


![Screenshot 2021-07-22 153354](https://user-images.githubusercontent.com/48810167/126698934-a2a20661-1637-4c2e-84eb-403983ead33c.png)

**Comment by Morabert** [comment] 2021-07-22 20:23
I used an older version of your mod to see if it would fix the problem.
The fact is your mod overwrites the basic diamond recipes and as result it can't be taken out because it creates fatal datapack errors.

I did all that with the Java and it only caused my game to crash.
But quite frankly; if your mod doesn't work properly with the default java settings than it doesn't work properly. 99.x% of users are not going to be able, much less willing, to change their Java settings properly.

[debug.log](https://github.com/AnonymousHacker1279/ImmersiveWeapons/files/6865012/debug.log)

**Comment by AnonymousHacker1279** [comment] 2021-07-22 21:33
I looked through the logs again. You are using Forge 36.1.0, you need 36.1.4 or higher for Java 16 features. It is also still using Java 8. If you would rather not deal with Java stuff, downgrade to v1.1.1 and see if that fixes the issue. 

The reason behind moving to Java 16 starting at v1.2.0 was because 1.17 would have required it anyways.

As for the datapack errors, I cannot find anything in the logs that reference my mod. However, the diamond recipe was removed in v1.2.0 so it should default to the vanilla one again.

Now that 1.17.1 has released for Forge (as of two hours ago), I'll try to create the final v1.4.0 release that will be back on Java 8. I'm almost done with it on my end.

**Comment by AnonymousHacker1279** [comment] 2021-07-22 22:02
I have released version v1.4.0. It targets Java 8, so you shouldn't need to worry about updating Java.

Let me know if the issue persists.

**Comment by Morabert** [comment] 2021-07-22 23:03
ok, I'll check and get back to you.

**Comment by Morabert** [comment] 2021-07-23 00:52
![Second D](https://user-images.githubusercontent.com/36409264/126726114-51f81e2f-8ba9-49ac-b1a2-96bd44704fa7.JPG)
![first D](https://user-images.githubusercontent.com/36409264/126726115-c4ece422-fd0c-4d67-a192-e516dee62215.JPG)
It Works Now, Thanks for all your Help!

**Comment by AnonymousHacker1279** [comment] 2021-07-23 01:14
No problem. Glad to see everything works properly.

**Closed by AnonymousHacker1279** 2021-07-23 01:14 UTC
